/* Runtime loader for librbp_math_lib (language-agnostic engine product).
 * Generated by scripts/r/gen_engine_api.py
 */

#define RBP_ENGINE_NO_MACROS 1
#include "engine_api.h"

#include <stdio.h>
#include <string.h>

#ifdef _WIN32
#include <windows.h>
#else
#include <dlfcn.h>
#endif

RbpEngineApi g_rbp_api;
static void *g_handle = NULL;
static char g_path[4096];
static int g_loaded = 0;

static void set_err(char *err_buf, int err_len, const char *msg) {
    if (err_buf && err_len > 0) {
        snprintf(err_buf, (size_t)err_len, "%s", msg ? msg : "unknown engine load error");
    }
}

static void clear_api(void) {
    memset(&g_rbp_api, 0, sizeof(g_rbp_api));
}

int rbp_engine_is_loaded(void) {
    return g_loaded;
}

const char *rbp_engine_loaded_path(void) {
    return g_loaded ? g_path : NULL;
}

void rbp_engine_unload(void) {
    if (g_handle) {
#ifdef _WIN32
        FreeLibrary((HMODULE)g_handle);
#else
        dlclose(g_handle);
#endif
        g_handle = NULL;
    }
    clear_api();
    g_path[0] = '\0';
    g_loaded = 0;
}

static void *sym(void *h, const char *name, char *err_buf, int err_len) {
#ifdef _WIN32
    FARPROC p = GetProcAddress((HMODULE)h, name);
    if (!p) {
        set_err(err_buf, err_len, name);
        return NULL;
    }
    return (void *)p;
#else
    dlerror();
    void *p = dlsym(h, name);
    const char *e = dlerror();
    if (e != NULL || p == NULL) {
        set_err(err_buf, err_len, e ? e : name);
        return NULL;
    }
    return p;
#endif
}

int rbp_engine_load(const char *path, char *err_buf, int err_len) {
    if (!path || !path[0]) {
        set_err(err_buf, err_len, "engine path is empty");
        return -1;
    }
    if (g_loaded && strcmp(g_path, path) == 0) {
        return 0;
    }
    if (g_loaded) {
        rbp_engine_unload();
    }

#ifdef _WIN32
    void *h = (void *)LoadLibraryA(path);
    if (!h) {
        set_err(err_buf, err_len, "LoadLibrary failed for RBP engine");
        return -1;
    }
#else
    void *h = dlopen(path, RTLD_NOW | RTLD_GLOBAL);
    if (!h) {
        const char *dle = dlerror();
        set_err(err_buf, err_len, dle ? dle : "dlopen failed");
        return -1;
    }
#endif
    g_handle = h;

    void *_s;
    _s = sym(h, "rbp_abi_version", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_abi_version) = _s;
    _s = sym(h, "rbp_get_percentile_value_algorithm", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_get_percentile_value_algorithm) = _s;
    _s = sym(h, "rbp_grid", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid) = _s;
    _s = sym(h, "rbp_grid_options_create", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_create) = _s;
    _s = sym(h, "rbp_grid_options_free", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_free) = _s;
    _s = sym(h, "rbp_grid_options_set_adj_fit_multiplier", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_adj_fit_multiplier) = _s;
    _s = sym(h, "rbp_grid_options_set_adjust_impact_for_missing", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_adjust_impact_for_missing) = _s;
    _s = sym(h, "rbp_grid_options_set_attribute_combi", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_attribute_combi) = _s;
    _s = sym(h, "rbp_grid_options_set_censor_operator", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_censor_operator) = _s;
    _s = sym(h, "rbp_grid_options_set_censor_type", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_censor_type) = _s;
    _s = sym(h, "rbp_grid_options_set_censor_unit", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_censor_unit) = _s;
    _s = sym(h, "rbp_grid_options_set_include_linear_regression", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_include_linear_regression) = _s;
    _s = sym(h, "rbp_grid_options_set_inner_parallel", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_inner_parallel) = _s;
    _s = sym(h, "rbp_grid_options_set_inv_method", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_inv_method) = _s;
    _s = sym(h, "rbp_grid_options_set_k", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_k) = _s;
    _s = sym(h, "rbp_grid_options_set_max_iter", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_max_iter) = _s;
    _s = sym(h, "rbp_grid_options_set_prediction_scale", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_prediction_scale) = _s;
    _s = sym(h, "rbp_grid_options_set_retain_all", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_retain_all) = _s;
    _s = sym(h, "rbp_grid_options_set_retain_grid_objects_str", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_retain_grid_objects_str) = _s;
    _s = sym(h, "rbp_grid_options_set_seed", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_seed) = _s;
    _s = sym(h, "rbp_grid_options_set_threshold", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_threshold) = _s;
    _s = sym(h, "rbp_grid_options_set_verbose", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_grid_options_set_verbose) = _s;
    _s = sym(h, "rbp_info_theta", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_info_theta) = _s;
    _s = sym(h, "rbp_info_x", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_info_x) = _s;
    _s = sym(h, "rbp_last_error", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_last_error) = _s;
    _s = sym(h, "rbp_maxfit", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit) = _s;
    _s = sym(h, "rbp_maxfit_options_create", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_create) = _s;
    _s = sym(h, "rbp_maxfit_options_free", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_free) = _s;
    _s = sym(h, "rbp_maxfit_options_set_adj_fit_multiplier", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_set_adj_fit_multiplier) = _s;
    _s = sym(h, "rbp_maxfit_options_set_censor_operator", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_set_censor_operator) = _s;
    _s = sym(h, "rbp_maxfit_options_set_censor_type", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_set_censor_type) = _s;
    _s = sym(h, "rbp_maxfit_options_set_censor_unit", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_set_censor_unit) = _s;
    _s = sym(h, "rbp_maxfit_options_set_include_linear_regression", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_set_include_linear_regression) = _s;
    _s = sym(h, "rbp_maxfit_options_set_inner_parallel", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_set_inner_parallel) = _s;
    _s = sym(h, "rbp_maxfit_options_set_inv_method", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_set_inv_method) = _s;
    _s = sym(h, "rbp_maxfit_options_set_missing_moments", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_set_missing_moments) = _s;
    _s = sym(h, "rbp_maxfit_options_set_objective", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_set_objective) = _s;
    _s = sym(h, "rbp_maxfit_options_set_prediction_scale", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_set_prediction_scale) = _s;
    _s = sym(h, "rbp_maxfit_options_set_threshold", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_set_threshold) = _s;
    _s = sym(h, "rbp_maxfit_options_set_verbose", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_set_verbose) = _s;
    _s = sym(h, "rbp_maxfit_options_set_verify_missing_data", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_maxfit_options_set_verify_missing_data) = _s;
    _s = sym(h, "rbp_predict", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict) = _s;
    _s = sym(h, "rbp_predict_options_create", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict_options_create) = _s;
    _s = sym(h, "rbp_predict_options_free", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict_options_free) = _s;
    _s = sym(h, "rbp_predict_options_set_adj_fit_multiplier", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict_options_set_adj_fit_multiplier) = _s;
    _s = sym(h, "rbp_predict_options_set_censor_operator", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict_options_set_censor_operator) = _s;
    _s = sym(h, "rbp_predict_options_set_censor_type", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict_options_set_censor_type) = _s;
    _s = sym(h, "rbp_predict_options_set_censor_unit", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict_options_set_censor_unit) = _s;
    _s = sym(h, "rbp_predict_options_set_include_linear_regression", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict_options_set_include_linear_regression) = _s;
    _s = sym(h, "rbp_predict_options_set_inv_method", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict_options_set_inv_method) = _s;
    _s = sym(h, "rbp_predict_options_set_missing_moments", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict_options_set_missing_moments) = _s;
    _s = sym(h, "rbp_predict_options_set_prediction_scale", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict_options_set_prediction_scale) = _s;
    _s = sym(h, "rbp_predict_options_set_threshold", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict_options_set_threshold) = _s;
    _s = sym(h, "rbp_predict_options_set_verbose", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict_options_set_verbose) = _s;
    _s = sym(h, "rbp_predict_options_set_verify_missing_data", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_predict_options_set_verify_missing_data) = _s;
    _s = sym(h, "rbp_prediction_results_free", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_prediction_results_free) = _s;
    _s = sym(h, "rbp_relevance", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_relevance) = _s;
    _s = sym(h, "rbp_relevance_metrics", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_relevance_metrics) = _s;
    _s = sym(h, "rbp_results_adjusted_fit_cells_dims", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_adjusted_fit_cells_dims) = _s;
    _s = sym(h, "rbp_results_combi_cells_dims", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_combi_cells_dims) = _s;
    _s = sym(h, "rbp_results_copy_adjusted_fit", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_adjusted_fit) = _s;
    _s = sym(h, "rbp_results_copy_adjusted_fit_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_adjusted_fit_cells) = _s;
    _s = sym(h, "rbp_results_copy_agreement", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_agreement) = _s;
    _s = sym(h, "rbp_results_copy_asymmetry", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_asymmetry) = _s;
    _s = sym(h, "rbp_results_copy_aux_full_var", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_aux_full_var) = _s;
    _s = sym(h, "rbp_results_copy_aux_k", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_aux_k) = _s;
    _s = sym(h, "rbp_results_copy_aux_lambda_sq", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_aux_lambda_sq) = _s;
    _s = sym(h, "rbp_results_copy_aux_n", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_aux_n) = _s;
    _s = sym(h, "rbp_results_copy_aux_part_var", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_aux_part_var) = _s;
    _s = sym(h, "rbp_results_copy_aux_phi", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_aux_phi) = _s;
    _s = sym(h, "rbp_results_copy_aux_r_star", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_aux_r_star) = _s;
    _s = sym(h, "rbp_results_copy_aux_r_star_percent", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_aux_r_star_percent) = _s;
    _s = sym(h, "rbp_results_copy_aux_rho", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_aux_rho) = _s;
    _s = sym(h, "rbp_results_copy_cctp", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_cctp) = _s;
    _s = sym(h, "rbp_results_copy_combi_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_combi_cells) = _s;
    _s = sym(h, "rbp_results_copy_fit", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_fit) = _s;
    _s = sym(h, "rbp_results_copy_include", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_include) = _s;
    _s = sym(h, "rbp_results_copy_info_theta", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_info_theta) = _s;
    _s = sym(h, "rbp_results_copy_info_x", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_info_x) = _s;
    _s = sym(h, "rbp_results_copy_k_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_k_cells) = _s;
    _s = sym(h, "rbp_results_copy_k_fit", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_k_fit) = _s;
    _s = sym(h, "rbp_results_copy_maxfit_index", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_maxfit_index) = _s;
    _s = sym(h, "rbp_results_copy_mctc", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_mctc) = _s;
    _s = sym(h, "rbp_results_copy_mctp", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_mctp) = _s;
    _s = sym(h, "rbp_results_copy_n_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_n_cells) = _s;
    _s = sym(h, "rbp_results_copy_outlier_influence", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_outlier_influence) = _s;
    _s = sym(h, "rbp_results_copy_relevance", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_relevance) = _s;
    _s = sym(h, "rbp_results_copy_similarity", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_similarity) = _s;
    _s = sym(h, "rbp_results_copy_thresholds", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_thresholds) = _s;
    _s = sym(h, "rbp_results_copy_variable_weights", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_variable_weights) = _s;
    _s = sym(h, "rbp_results_copy_weights", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_weights) = _s;
    _s = sym(h, "rbp_results_copy_weights_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_weights_cells) = _s;
    _s = sym(h, "rbp_results_copy_weights_concentration", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_weights_concentration) = _s;
    _s = sym(h, "rbp_results_copy_weights_excluded", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_weights_excluded) = _s;
    _s = sym(h, "rbp_results_copy_xi_solo", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_xi_solo) = _s;
    _s = sym(h, "rbp_results_copy_xi_solo_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_xi_solo_cells) = _s;
    _s = sym(h, "rbp_results_copy_xi_solo_composite", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_xi_solo_composite) = _s;
    _s = sym(h, "rbp_results_copy_y_solo", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_y_solo) = _s;
    _s = sym(h, "rbp_results_copy_yhat", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_yhat) = _s;
    _s = sym(h, "rbp_results_copy_yhat_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_yhat_cells) = _s;
    _s = sym(h, "rbp_results_copy_yhat_linear", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_yhat_linear) = _s;
    _s = sym(h, "rbp_results_copy_ysolo_bimodal_index", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_ysolo_bimodal_index) = _s;
    _s = sym(h, "rbp_results_copy_ysolo_bin_centers", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_ysolo_bin_centers) = _s;
    _s = sym(h, "rbp_results_copy_ysolo_bin_counts", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_ysolo_bin_counts) = _s;
    _s = sym(h, "rbp_results_copy_ysolo_bin_edges", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_ysolo_bin_edges) = _s;
    _s = sym(h, "rbp_results_copy_ysolo_bin_widths", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_ysolo_bin_widths) = _s;
    _s = sym(h, "rbp_results_copy_ysolo_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_ysolo_cells) = _s;
    _s = sym(h, "rbp_results_copy_ysolo_kurtosis", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_ysolo_kurtosis) = _s;
    _s = sym(h, "rbp_results_copy_ysolo_pearson_modality_index", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_ysolo_pearson_modality_index) = _s;
    _s = sym(h, "rbp_results_copy_ysolo_sigma", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_ysolo_sigma) = _s;
    _s = sym(h, "rbp_results_copy_ysolo_skewness", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_copy_ysolo_skewness) = _s;
    _s = sym(h, "rbp_results_has_adjusted_fit_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_adjusted_fit_cells) = _s;
    _s = sym(h, "rbp_results_has_auxiliary", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_auxiliary) = _s;
    _s = sym(h, "rbp_results_has_combi_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_combi_cells) = _s;
    _s = sym(h, "rbp_results_has_grid_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_grid_cells) = _s;
    _s = sym(h, "rbp_results_has_grid_insights", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_grid_insights) = _s;
    _s = sym(h, "rbp_results_has_include", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_include) = _s;
    _s = sym(h, "rbp_results_has_k_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_k_cells) = _s;
    _s = sym(h, "rbp_results_has_maxfit_index", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_maxfit_index) = _s;
    _s = sym(h, "rbp_results_has_n_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_n_cells) = _s;
    _s = sym(h, "rbp_results_has_weights", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_weights) = _s;
    _s = sym(h, "rbp_results_has_weights_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_weights_cells) = _s;
    _s = sym(h, "rbp_results_has_weights_excluded", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_weights_excluded) = _s;
    _s = sym(h, "rbp_results_has_xi_solo", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_xi_solo) = _s;
    _s = sym(h, "rbp_results_has_xi_solo_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_xi_solo_cells) = _s;
    _s = sym(h, "rbp_results_has_y_solo", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_y_solo) = _s;
    _s = sym(h, "rbp_results_has_yhat_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_yhat_cells) = _s;
    _s = sym(h, "rbp_results_has_yhat_linear", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_yhat_linear) = _s;
    _s = sym(h, "rbp_results_has_ysolo_cells", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_ysolo_cells) = _s;
    _s = sym(h, "rbp_results_has_ysolo_distribution", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_has_ysolo_distribution) = _s;
    _s = sym(h, "rbp_results_include_dims", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_include_dims) = _s;
    _s = sym(h, "rbp_results_k_cells_dims", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_k_cells_dims) = _s;
    _s = sym(h, "rbp_results_maxfit_index_len", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_maxfit_index_len) = _s;
    _s = sym(h, "rbp_results_n_cells_dims", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_n_cells_dims) = _s;
    _s = sym(h, "rbp_results_num_observations", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_num_observations) = _s;
    _s = sym(h, "rbp_results_num_thresholds", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_num_thresholds) = _s;
    _s = sym(h, "rbp_results_num_variables", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_num_variables) = _s;
    _s = sym(h, "rbp_results_weights_cells_dims", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_weights_cells_dims) = _s;
    _s = sym(h, "rbp_results_weights_dims", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_weights_dims) = _s;
    _s = sym(h, "rbp_results_weights_excluded_dims", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_weights_excluded_dims) = _s;
    _s = sym(h, "rbp_results_xi_solo_cells_dims", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_xi_solo_cells_dims) = _s;
    _s = sym(h, "rbp_results_xi_solo_dims", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_xi_solo_dims) = _s;
    _s = sym(h, "rbp_results_yhat_cells_dims", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_yhat_cells_dims) = _s;
    _s = sym(h, "rbp_results_ysolo_cells_dims", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_ysolo_cells_dims) = _s;
    _s = sym(h, "rbp_results_ysolo_distribution_dims", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_results_ysolo_distribution_dims) = _s;
    _s = sym(h, "rbp_set_percentile_value_algorithm", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_set_percentile_value_algorithm) = _s;
    _s = sym(h, "rbp_set_percentile_value_algorithm_str", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_set_percentile_value_algorithm_str) = _s;
    _s = sym(h, "rbp_similarity", err_buf, err_len);
    if (!_s) { rbp_engine_unload(); return -1; }
    *(void **)(&g_rbp_api.p_rbp_similarity) = _s;
    strncpy(g_path, path, sizeof(g_path) - 1);
    g_path[sizeof(g_path) - 1] = '\0';
    g_loaded = 1;
    return 0;
}
