/* Runtime function-pointer table for the RBP engine (dlopen / LoadLibrary).
 * Generated by scripts/r/gen_engine_api.py — do not hand-edit symbol lists.
 */
#ifndef RBP_ENGINE_API_H
#define RBP_ENGINE_API_H

#include "rbp_math.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct RbpEngineApi {
    uint32_t (*p_rbp_abi_version)(void);
    int32_t (*p_rbp_get_percentile_value_algorithm)(void);
    RbpStatus (*p_rbp_grid)(const double *y, size_t n, const double *x, size_t n_rows, size_t n_cols, int32_t x_layout, const double *theta, size_t k, const RbpGridOptions *options, RbpPredictionResults **out_results);
    RbpGridOptions * (*p_rbp_grid_options_create)(void);
    void (*p_rbp_grid_options_free)(RbpGridOptions *opts);
    RbpStatus (*p_rbp_grid_options_set_adj_fit_multiplier)(RbpGridOptions *opts, int32_t value);
    RbpStatus (*p_rbp_grid_options_set_adjust_impact_for_missing)(RbpGridOptions *opts, int32_t value);
    RbpStatus (*p_rbp_grid_options_set_attribute_combi)(RbpGridOptions *opts, const double *data, size_t n_rows, size_t n_cols, int32_t layout);
    RbpStatus (*p_rbp_grid_options_set_censor_operator)(RbpGridOptions *opts, int32_t value);
    RbpStatus (*p_rbp_grid_options_set_censor_type)(RbpGridOptions *opts, int32_t value);
    RbpStatus (*p_rbp_grid_options_set_censor_unit)(RbpGridOptions *opts, int32_t value);
    RbpStatus (*p_rbp_grid_options_set_include_linear_regression)(RbpGridOptions *opts, int32_t value);
    RbpStatus (*p_rbp_grid_options_set_inner_parallel)(RbpGridOptions *opts, int32_t value);
    RbpStatus (*p_rbp_grid_options_set_inv_method)(RbpGridOptions *opts, int32_t value);
    RbpStatus (*p_rbp_grid_options_set_k)(RbpGridOptions *opts, size_t value);
    RbpStatus (*p_rbp_grid_options_set_max_iter)(RbpGridOptions *opts, size_t value);
    RbpStatus (*p_rbp_grid_options_set_prediction_scale)(RbpGridOptions *opts, int32_t value);
    RbpStatus (*p_rbp_grid_options_set_retain_all)(RbpGridOptions *opts, int32_t value);
    RbpStatus (*p_rbp_grid_options_set_retain_grid_objects_str)(RbpGridOptions *opts, const char *value);
    RbpStatus (*p_rbp_grid_options_set_seed)(RbpGridOptions *opts, uint32_t value);
    RbpStatus (*p_rbp_grid_options_set_threshold)(RbpGridOptions *opts, const double *values, size_t len);
    RbpStatus (*p_rbp_grid_options_set_verbose)(RbpGridOptions *opts, int32_t value);
    RbpStatus (*p_rbp_info_theta)(const double *x, size_t n_rows, size_t n_cols, int32_t x_layout, const double *theta, size_t k, const double *cov_inv, int32_t cov_inv_layout, double *out, size_t out_len);
    RbpStatus (*p_rbp_info_x)(const double *x, size_t n_rows, size_t n_cols, int32_t x_layout, const double *cov_inv, int32_t cov_inv_layout, double *out, size_t out_len);
    const char * (*p_rbp_last_error)(void);
    RbpStatus (*p_rbp_maxfit)(const double *y, size_t n, const double *x, size_t n_rows, size_t n_cols, int32_t x_layout, const double *theta, size_t k, const RbpMaxFitOptions *options, RbpPredictionResults **out_results);
    RbpMaxFitOptions * (*p_rbp_maxfit_options_create)(void);
    void (*p_rbp_maxfit_options_free)(RbpMaxFitOptions *opts);
    RbpStatus (*p_rbp_maxfit_options_set_adj_fit_multiplier)(RbpMaxFitOptions *opts, int32_t value);
    RbpStatus (*p_rbp_maxfit_options_set_censor_operator)(RbpMaxFitOptions *opts, int32_t value);
    RbpStatus (*p_rbp_maxfit_options_set_censor_type)(RbpMaxFitOptions *opts, int32_t value);
    RbpStatus (*p_rbp_maxfit_options_set_censor_unit)(RbpMaxFitOptions *opts, int32_t value);
    RbpStatus (*p_rbp_maxfit_options_set_include_linear_regression)(RbpMaxFitOptions *opts, int32_t value);
    RbpStatus (*p_rbp_maxfit_options_set_inner_parallel)(RbpMaxFitOptions *opts, int32_t value);
    RbpStatus (*p_rbp_maxfit_options_set_inv_method)(RbpMaxFitOptions *opts, int32_t value);
    RbpStatus (*p_rbp_maxfit_options_set_missing_moments)(RbpMaxFitOptions *opts, int32_t value);
    RbpStatus (*p_rbp_maxfit_options_set_objective)(RbpMaxFitOptions *opts, const char *value);
    RbpStatus (*p_rbp_maxfit_options_set_prediction_scale)(RbpMaxFitOptions *opts, int32_t value);
    RbpStatus (*p_rbp_maxfit_options_set_threshold)(RbpMaxFitOptions *opts, const double *values, size_t len);
    RbpStatus (*p_rbp_maxfit_options_set_verbose)(RbpMaxFitOptions *opts, int32_t value);
    RbpStatus (*p_rbp_maxfit_options_set_verify_missing_data)(RbpMaxFitOptions *opts, int32_t value);
    RbpStatus (*p_rbp_predict)(const double *y, size_t n, const double *x, size_t n_rows, size_t n_cols, int32_t x_layout, const double *theta, size_t k, const RbpPredictOptions *options, RbpPredictionResults **out_results);
    RbpPredictOptions * (*p_rbp_predict_options_create)(void);
    void (*p_rbp_predict_options_free)(RbpPredictOptions *opts);
    RbpStatus (*p_rbp_predict_options_set_adj_fit_multiplier)(RbpPredictOptions *opts, int32_t value);
    RbpStatus (*p_rbp_predict_options_set_censor_operator)(RbpPredictOptions *opts, int32_t value);
    RbpStatus (*p_rbp_predict_options_set_censor_type)(RbpPredictOptions *opts, int32_t value);
    RbpStatus (*p_rbp_predict_options_set_censor_unit)(RbpPredictOptions *opts, int32_t value);
    RbpStatus (*p_rbp_predict_options_set_include_linear_regression)(RbpPredictOptions *opts, int32_t value);
    RbpStatus (*p_rbp_predict_options_set_inv_method)(RbpPredictOptions *opts, int32_t value);
    RbpStatus (*p_rbp_predict_options_set_missing_moments)(RbpPredictOptions *opts, int32_t value);
    RbpStatus (*p_rbp_predict_options_set_prediction_scale)(RbpPredictOptions *opts, int32_t value);
    RbpStatus (*p_rbp_predict_options_set_threshold)(RbpPredictOptions *opts, const double *values, size_t len);
    RbpStatus (*p_rbp_predict_options_set_verbose)(RbpPredictOptions *opts, int32_t value);
    RbpStatus (*p_rbp_predict_options_set_verify_missing_data)(RbpPredictOptions *opts, int32_t value);
    void (*p_rbp_prediction_results_free)(RbpPredictionResults *results);
    RbpStatus (*p_rbp_relevance)(const double *x, size_t n_rows, size_t n_cols, int32_t x_layout, const double *theta, size_t k, const double *cov_inv, int32_t cov_inv_layout, double *out, size_t out_len);
    RbpStatus (*p_rbp_relevance_metrics)(const double *x, size_t n_rows, size_t n_cols, int32_t x_layout, const double *theta, size_t k, const double *cov_inv, int32_t cov_inv_layout, double *out_relevance, size_t out_relevance_len, double *out_similarity, size_t out_similarity_len, double *out_info_x, size_t out_info_x_len, double *out_info_theta, size_t out_info_theta_len);
    RbpStatus (*p_rbp_results_adjusted_fit_cells_dims)(const RbpPredictionResults *results, int32_t censor, size_t *out_rows, size_t *out_cols);
    RbpStatus (*p_rbp_results_combi_cells_dims)(const RbpPredictionResults *results, size_t *out_rows, size_t *out_cols);
    RbpStatus (*p_rbp_results_copy_adjusted_fit)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_adjusted_fit_cells)(const RbpPredictionResults *results, int32_t censor, double *out, size_t len, int32_t layout);
    RbpStatus (*p_rbp_results_copy_agreement)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_asymmetry)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_aux_full_var)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_aux_k)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_aux_lambda_sq)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_aux_n)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_aux_part_var)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_aux_phi)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_aux_r_star)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_aux_r_star_percent)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_aux_rho)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_cctp)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_combi_cells)(const RbpPredictionResults *results, double *out, size_t len, int32_t layout);
    RbpStatus (*p_rbp_results_copy_fit)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_include)(const RbpPredictionResults *results, uint8_t *out, size_t len, int32_t layout);
    RbpStatus (*p_rbp_results_copy_info_theta)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_info_x)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_k_cells)(const RbpPredictionResults *results, double *out, size_t len, int32_t layout);
    RbpStatus (*p_rbp_results_copy_k_fit)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_maxfit_index)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_mctc)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_mctp)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_n_cells)(const RbpPredictionResults *results, int32_t censor, double *out, size_t len, int32_t layout);
    RbpStatus (*p_rbp_results_copy_outlier_influence)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_relevance)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_similarity)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_thresholds)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_variable_weights)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_weights)(const RbpPredictionResults *results, double *out, size_t len, int32_t layout);
    RbpStatus (*p_rbp_results_copy_weights_cells)(const RbpPredictionResults *results, int32_t censor, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_weights_concentration)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_weights_excluded)(const RbpPredictionResults *results, double *out, size_t len, int32_t layout);
    RbpStatus (*p_rbp_results_copy_xi_solo)(const RbpPredictionResults *results, double *out, size_t len, int32_t layout);
    RbpStatus (*p_rbp_results_copy_xi_solo_cells)(const RbpPredictionResults *results, int32_t censor, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_xi_solo_composite)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_y_solo)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_yhat)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_yhat_cells)(const RbpPredictionResults *results, int32_t censor, double *out, size_t len, int32_t layout);
    RbpStatus (*p_rbp_results_copy_yhat_linear)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_ysolo_bimodal_index)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_ysolo_bin_centers)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_ysolo_bin_counts)(const RbpPredictionResults *results, double *out, size_t len, int32_t layout);
    RbpStatus (*p_rbp_results_copy_ysolo_bin_edges)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_ysolo_bin_widths)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_ysolo_cells)(const RbpPredictionResults *results, double *out, size_t len, int32_t layout);
    RbpStatus (*p_rbp_results_copy_ysolo_kurtosis)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_ysolo_pearson_modality_index)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_ysolo_sigma)(const RbpPredictionResults *results, double *out, size_t len);
    RbpStatus (*p_rbp_results_copy_ysolo_skewness)(const RbpPredictionResults *results, double *out, size_t len);
    int32_t (*p_rbp_results_has_adjusted_fit_cells)(const RbpPredictionResults *results, int32_t censor);
    int32_t (*p_rbp_results_has_auxiliary)(const RbpPredictionResults *results);
    int32_t (*p_rbp_results_has_combi_cells)(const RbpPredictionResults *results);
    int32_t (*p_rbp_results_has_grid_cells)(const RbpPredictionResults *results);
    int32_t (*p_rbp_results_has_grid_insights)(const RbpPredictionResults *results);
    int32_t (*p_rbp_results_has_include)(const RbpPredictionResults *results);
    int32_t (*p_rbp_results_has_k_cells)(const RbpPredictionResults *results);
    int32_t (*p_rbp_results_has_maxfit_index)(const RbpPredictionResults *results);
    int32_t (*p_rbp_results_has_n_cells)(const RbpPredictionResults *results, int32_t censor);
    int32_t (*p_rbp_results_has_weights)(const RbpPredictionResults *results);
    int32_t (*p_rbp_results_has_weights_cells)(const RbpPredictionResults *results, int32_t censor);
    int32_t (*p_rbp_results_has_weights_excluded)(const RbpPredictionResults *results);
    int32_t (*p_rbp_results_has_xi_solo)(const RbpPredictionResults *results);
    int32_t (*p_rbp_results_has_xi_solo_cells)(const RbpPredictionResults *results, int32_t censor);
    int32_t (*p_rbp_results_has_y_solo)(const RbpPredictionResults *results);
    int32_t (*p_rbp_results_has_yhat_cells)(const RbpPredictionResults *results, int32_t censor);
    int32_t (*p_rbp_results_has_yhat_linear)(const RbpPredictionResults *results);
    int32_t (*p_rbp_results_has_ysolo_cells)(const RbpPredictionResults *results);
    int32_t (*p_rbp_results_has_ysolo_distribution)(const RbpPredictionResults *results);
    RbpStatus (*p_rbp_results_include_dims)(const RbpPredictionResults *results, size_t *out_rows, size_t *out_cols);
    RbpStatus (*p_rbp_results_k_cells_dims)(const RbpPredictionResults *results, size_t *out_rows, size_t *out_cols);
    size_t (*p_rbp_results_maxfit_index_len)(const RbpPredictionResults *results);
    RbpStatus (*p_rbp_results_n_cells_dims)(const RbpPredictionResults *results, int32_t censor, size_t *out_rows, size_t *out_cols);
    size_t (*p_rbp_results_num_observations)(const RbpPredictionResults *results);
    size_t (*p_rbp_results_num_thresholds)(const RbpPredictionResults *results);
    size_t (*p_rbp_results_num_variables)(const RbpPredictionResults *results);
    RbpStatus (*p_rbp_results_weights_cells_dims)(const RbpPredictionResults *results, int32_t censor, size_t *out_d0, size_t *out_d1, size_t *out_d2);
    RbpStatus (*p_rbp_results_weights_dims)(const RbpPredictionResults *results, size_t *out_rows, size_t *out_cols);
    RbpStatus (*p_rbp_results_weights_excluded_dims)(const RbpPredictionResults *results, size_t *out_rows, size_t *out_cols);
    RbpStatus (*p_rbp_results_xi_solo_cells_dims)(const RbpPredictionResults *results, int32_t censor, size_t *out_d0, size_t *out_d1, size_t *out_d2);
    RbpStatus (*p_rbp_results_xi_solo_dims)(const RbpPredictionResults *results, size_t *out_rows, size_t *out_cols);
    RbpStatus (*p_rbp_results_yhat_cells_dims)(const RbpPredictionResults *results, int32_t censor, size_t *out_rows, size_t *out_cols);
    RbpStatus (*p_rbp_results_ysolo_cells_dims)(const RbpPredictionResults *results, size_t *out_rows, size_t *out_cols);
    RbpStatus (*p_rbp_results_ysolo_distribution_dims)(const RbpPredictionResults *results, size_t *out_n_bins, size_t *out_n_cols);
    RbpStatus (*p_rbp_set_percentile_value_algorithm)(int32_t algorithm);
    RbpStatus (*p_rbp_set_percentile_value_algorithm_str)(const char *value);
    RbpStatus (*p_rbp_similarity)(const double *x, size_t n_rows, size_t n_cols, int32_t x_layout, const double *theta, size_t k, const double *cov_inv, int32_t cov_inv_layout, double *out, size_t out_len);
} RbpEngineApi;

extern RbpEngineApi g_rbp_api;

int rbp_engine_load(const char *path, char *err_buf, int err_len);
int rbp_engine_is_loaded(void);
const char *rbp_engine_loaded_path(void);
void rbp_engine_unload(void);

#ifndef RBP_ENGINE_NO_MACROS
#define rbp_abi_version (g_rbp_api.p_rbp_abi_version)
#define rbp_get_percentile_value_algorithm (g_rbp_api.p_rbp_get_percentile_value_algorithm)
#define rbp_grid (g_rbp_api.p_rbp_grid)
#define rbp_grid_options_create (g_rbp_api.p_rbp_grid_options_create)
#define rbp_grid_options_free (g_rbp_api.p_rbp_grid_options_free)
#define rbp_grid_options_set_adj_fit_multiplier (g_rbp_api.p_rbp_grid_options_set_adj_fit_multiplier)
#define rbp_grid_options_set_adjust_impact_for_missing (g_rbp_api.p_rbp_grid_options_set_adjust_impact_for_missing)
#define rbp_grid_options_set_attribute_combi (g_rbp_api.p_rbp_grid_options_set_attribute_combi)
#define rbp_grid_options_set_censor_operator (g_rbp_api.p_rbp_grid_options_set_censor_operator)
#define rbp_grid_options_set_censor_type (g_rbp_api.p_rbp_grid_options_set_censor_type)
#define rbp_grid_options_set_censor_unit (g_rbp_api.p_rbp_grid_options_set_censor_unit)
#define rbp_grid_options_set_include_linear_regression (g_rbp_api.p_rbp_grid_options_set_include_linear_regression)
#define rbp_grid_options_set_inner_parallel (g_rbp_api.p_rbp_grid_options_set_inner_parallel)
#define rbp_grid_options_set_inv_method (g_rbp_api.p_rbp_grid_options_set_inv_method)
#define rbp_grid_options_set_k (g_rbp_api.p_rbp_grid_options_set_k)
#define rbp_grid_options_set_max_iter (g_rbp_api.p_rbp_grid_options_set_max_iter)
#define rbp_grid_options_set_prediction_scale (g_rbp_api.p_rbp_grid_options_set_prediction_scale)
#define rbp_grid_options_set_retain_all (g_rbp_api.p_rbp_grid_options_set_retain_all)
#define rbp_grid_options_set_retain_grid_objects_str (g_rbp_api.p_rbp_grid_options_set_retain_grid_objects_str)
#define rbp_grid_options_set_seed (g_rbp_api.p_rbp_grid_options_set_seed)
#define rbp_grid_options_set_threshold (g_rbp_api.p_rbp_grid_options_set_threshold)
#define rbp_grid_options_set_verbose (g_rbp_api.p_rbp_grid_options_set_verbose)
#define rbp_info_theta (g_rbp_api.p_rbp_info_theta)
#define rbp_info_x (g_rbp_api.p_rbp_info_x)
#define rbp_last_error (g_rbp_api.p_rbp_last_error)
#define rbp_maxfit (g_rbp_api.p_rbp_maxfit)
#define rbp_maxfit_options_create (g_rbp_api.p_rbp_maxfit_options_create)
#define rbp_maxfit_options_free (g_rbp_api.p_rbp_maxfit_options_free)
#define rbp_maxfit_options_set_adj_fit_multiplier (g_rbp_api.p_rbp_maxfit_options_set_adj_fit_multiplier)
#define rbp_maxfit_options_set_censor_operator (g_rbp_api.p_rbp_maxfit_options_set_censor_operator)
#define rbp_maxfit_options_set_censor_type (g_rbp_api.p_rbp_maxfit_options_set_censor_type)
#define rbp_maxfit_options_set_censor_unit (g_rbp_api.p_rbp_maxfit_options_set_censor_unit)
#define rbp_maxfit_options_set_include_linear_regression (g_rbp_api.p_rbp_maxfit_options_set_include_linear_regression)
#define rbp_maxfit_options_set_inner_parallel (g_rbp_api.p_rbp_maxfit_options_set_inner_parallel)
#define rbp_maxfit_options_set_inv_method (g_rbp_api.p_rbp_maxfit_options_set_inv_method)
#define rbp_maxfit_options_set_missing_moments (g_rbp_api.p_rbp_maxfit_options_set_missing_moments)
#define rbp_maxfit_options_set_objective (g_rbp_api.p_rbp_maxfit_options_set_objective)
#define rbp_maxfit_options_set_prediction_scale (g_rbp_api.p_rbp_maxfit_options_set_prediction_scale)
#define rbp_maxfit_options_set_threshold (g_rbp_api.p_rbp_maxfit_options_set_threshold)
#define rbp_maxfit_options_set_verbose (g_rbp_api.p_rbp_maxfit_options_set_verbose)
#define rbp_maxfit_options_set_verify_missing_data (g_rbp_api.p_rbp_maxfit_options_set_verify_missing_data)
#define rbp_predict (g_rbp_api.p_rbp_predict)
#define rbp_predict_options_create (g_rbp_api.p_rbp_predict_options_create)
#define rbp_predict_options_free (g_rbp_api.p_rbp_predict_options_free)
#define rbp_predict_options_set_adj_fit_multiplier (g_rbp_api.p_rbp_predict_options_set_adj_fit_multiplier)
#define rbp_predict_options_set_censor_operator (g_rbp_api.p_rbp_predict_options_set_censor_operator)
#define rbp_predict_options_set_censor_type (g_rbp_api.p_rbp_predict_options_set_censor_type)
#define rbp_predict_options_set_censor_unit (g_rbp_api.p_rbp_predict_options_set_censor_unit)
#define rbp_predict_options_set_include_linear_regression (g_rbp_api.p_rbp_predict_options_set_include_linear_regression)
#define rbp_predict_options_set_inv_method (g_rbp_api.p_rbp_predict_options_set_inv_method)
#define rbp_predict_options_set_missing_moments (g_rbp_api.p_rbp_predict_options_set_missing_moments)
#define rbp_predict_options_set_prediction_scale (g_rbp_api.p_rbp_predict_options_set_prediction_scale)
#define rbp_predict_options_set_threshold (g_rbp_api.p_rbp_predict_options_set_threshold)
#define rbp_predict_options_set_verbose (g_rbp_api.p_rbp_predict_options_set_verbose)
#define rbp_predict_options_set_verify_missing_data (g_rbp_api.p_rbp_predict_options_set_verify_missing_data)
#define rbp_prediction_results_free (g_rbp_api.p_rbp_prediction_results_free)
#define rbp_relevance (g_rbp_api.p_rbp_relevance)
#define rbp_relevance_metrics (g_rbp_api.p_rbp_relevance_metrics)
#define rbp_results_adjusted_fit_cells_dims (g_rbp_api.p_rbp_results_adjusted_fit_cells_dims)
#define rbp_results_combi_cells_dims (g_rbp_api.p_rbp_results_combi_cells_dims)
#define rbp_results_copy_adjusted_fit (g_rbp_api.p_rbp_results_copy_adjusted_fit)
#define rbp_results_copy_adjusted_fit_cells (g_rbp_api.p_rbp_results_copy_adjusted_fit_cells)
#define rbp_results_copy_agreement (g_rbp_api.p_rbp_results_copy_agreement)
#define rbp_results_copy_asymmetry (g_rbp_api.p_rbp_results_copy_asymmetry)
#define rbp_results_copy_aux_full_var (g_rbp_api.p_rbp_results_copy_aux_full_var)
#define rbp_results_copy_aux_k (g_rbp_api.p_rbp_results_copy_aux_k)
#define rbp_results_copy_aux_lambda_sq (g_rbp_api.p_rbp_results_copy_aux_lambda_sq)
#define rbp_results_copy_aux_n (g_rbp_api.p_rbp_results_copy_aux_n)
#define rbp_results_copy_aux_part_var (g_rbp_api.p_rbp_results_copy_aux_part_var)
#define rbp_results_copy_aux_phi (g_rbp_api.p_rbp_results_copy_aux_phi)
#define rbp_results_copy_aux_r_star (g_rbp_api.p_rbp_results_copy_aux_r_star)
#define rbp_results_copy_aux_r_star_percent (g_rbp_api.p_rbp_results_copy_aux_r_star_percent)
#define rbp_results_copy_aux_rho (g_rbp_api.p_rbp_results_copy_aux_rho)
#define rbp_results_copy_cctp (g_rbp_api.p_rbp_results_copy_cctp)
#define rbp_results_copy_combi_cells (g_rbp_api.p_rbp_results_copy_combi_cells)
#define rbp_results_copy_fit (g_rbp_api.p_rbp_results_copy_fit)
#define rbp_results_copy_include (g_rbp_api.p_rbp_results_copy_include)
#define rbp_results_copy_info_theta (g_rbp_api.p_rbp_results_copy_info_theta)
#define rbp_results_copy_info_x (g_rbp_api.p_rbp_results_copy_info_x)
#define rbp_results_copy_k_cells (g_rbp_api.p_rbp_results_copy_k_cells)
#define rbp_results_copy_k_fit (g_rbp_api.p_rbp_results_copy_k_fit)
#define rbp_results_copy_maxfit_index (g_rbp_api.p_rbp_results_copy_maxfit_index)
#define rbp_results_copy_mctc (g_rbp_api.p_rbp_results_copy_mctc)
#define rbp_results_copy_mctp (g_rbp_api.p_rbp_results_copy_mctp)
#define rbp_results_copy_n_cells (g_rbp_api.p_rbp_results_copy_n_cells)
#define rbp_results_copy_outlier_influence (g_rbp_api.p_rbp_results_copy_outlier_influence)
#define rbp_results_copy_relevance (g_rbp_api.p_rbp_results_copy_relevance)
#define rbp_results_copy_similarity (g_rbp_api.p_rbp_results_copy_similarity)
#define rbp_results_copy_thresholds (g_rbp_api.p_rbp_results_copy_thresholds)
#define rbp_results_copy_variable_weights (g_rbp_api.p_rbp_results_copy_variable_weights)
#define rbp_results_copy_weights (g_rbp_api.p_rbp_results_copy_weights)
#define rbp_results_copy_weights_cells (g_rbp_api.p_rbp_results_copy_weights_cells)
#define rbp_results_copy_weights_concentration (g_rbp_api.p_rbp_results_copy_weights_concentration)
#define rbp_results_copy_weights_excluded (g_rbp_api.p_rbp_results_copy_weights_excluded)
#define rbp_results_copy_xi_solo (g_rbp_api.p_rbp_results_copy_xi_solo)
#define rbp_results_copy_xi_solo_cells (g_rbp_api.p_rbp_results_copy_xi_solo_cells)
#define rbp_results_copy_xi_solo_composite (g_rbp_api.p_rbp_results_copy_xi_solo_composite)
#define rbp_results_copy_y_solo (g_rbp_api.p_rbp_results_copy_y_solo)
#define rbp_results_copy_yhat (g_rbp_api.p_rbp_results_copy_yhat)
#define rbp_results_copy_yhat_cells (g_rbp_api.p_rbp_results_copy_yhat_cells)
#define rbp_results_copy_yhat_linear (g_rbp_api.p_rbp_results_copy_yhat_linear)
#define rbp_results_copy_ysolo_bimodal_index (g_rbp_api.p_rbp_results_copy_ysolo_bimodal_index)
#define rbp_results_copy_ysolo_bin_centers (g_rbp_api.p_rbp_results_copy_ysolo_bin_centers)
#define rbp_results_copy_ysolo_bin_counts (g_rbp_api.p_rbp_results_copy_ysolo_bin_counts)
#define rbp_results_copy_ysolo_bin_edges (g_rbp_api.p_rbp_results_copy_ysolo_bin_edges)
#define rbp_results_copy_ysolo_bin_widths (g_rbp_api.p_rbp_results_copy_ysolo_bin_widths)
#define rbp_results_copy_ysolo_cells (g_rbp_api.p_rbp_results_copy_ysolo_cells)
#define rbp_results_copy_ysolo_kurtosis (g_rbp_api.p_rbp_results_copy_ysolo_kurtosis)
#define rbp_results_copy_ysolo_pearson_modality_index (g_rbp_api.p_rbp_results_copy_ysolo_pearson_modality_index)
#define rbp_results_copy_ysolo_sigma (g_rbp_api.p_rbp_results_copy_ysolo_sigma)
#define rbp_results_copy_ysolo_skewness (g_rbp_api.p_rbp_results_copy_ysolo_skewness)
#define rbp_results_has_adjusted_fit_cells (g_rbp_api.p_rbp_results_has_adjusted_fit_cells)
#define rbp_results_has_auxiliary (g_rbp_api.p_rbp_results_has_auxiliary)
#define rbp_results_has_combi_cells (g_rbp_api.p_rbp_results_has_combi_cells)
#define rbp_results_has_grid_cells (g_rbp_api.p_rbp_results_has_grid_cells)
#define rbp_results_has_grid_insights (g_rbp_api.p_rbp_results_has_grid_insights)
#define rbp_results_has_include (g_rbp_api.p_rbp_results_has_include)
#define rbp_results_has_k_cells (g_rbp_api.p_rbp_results_has_k_cells)
#define rbp_results_has_maxfit_index (g_rbp_api.p_rbp_results_has_maxfit_index)
#define rbp_results_has_n_cells (g_rbp_api.p_rbp_results_has_n_cells)
#define rbp_results_has_weights (g_rbp_api.p_rbp_results_has_weights)
#define rbp_results_has_weights_cells (g_rbp_api.p_rbp_results_has_weights_cells)
#define rbp_results_has_weights_excluded (g_rbp_api.p_rbp_results_has_weights_excluded)
#define rbp_results_has_xi_solo (g_rbp_api.p_rbp_results_has_xi_solo)
#define rbp_results_has_xi_solo_cells (g_rbp_api.p_rbp_results_has_xi_solo_cells)
#define rbp_results_has_y_solo (g_rbp_api.p_rbp_results_has_y_solo)
#define rbp_results_has_yhat_cells (g_rbp_api.p_rbp_results_has_yhat_cells)
#define rbp_results_has_yhat_linear (g_rbp_api.p_rbp_results_has_yhat_linear)
#define rbp_results_has_ysolo_cells (g_rbp_api.p_rbp_results_has_ysolo_cells)
#define rbp_results_has_ysolo_distribution (g_rbp_api.p_rbp_results_has_ysolo_distribution)
#define rbp_results_include_dims (g_rbp_api.p_rbp_results_include_dims)
#define rbp_results_k_cells_dims (g_rbp_api.p_rbp_results_k_cells_dims)
#define rbp_results_maxfit_index_len (g_rbp_api.p_rbp_results_maxfit_index_len)
#define rbp_results_n_cells_dims (g_rbp_api.p_rbp_results_n_cells_dims)
#define rbp_results_num_observations (g_rbp_api.p_rbp_results_num_observations)
#define rbp_results_num_thresholds (g_rbp_api.p_rbp_results_num_thresholds)
#define rbp_results_num_variables (g_rbp_api.p_rbp_results_num_variables)
#define rbp_results_weights_cells_dims (g_rbp_api.p_rbp_results_weights_cells_dims)
#define rbp_results_weights_dims (g_rbp_api.p_rbp_results_weights_dims)
#define rbp_results_weights_excluded_dims (g_rbp_api.p_rbp_results_weights_excluded_dims)
#define rbp_results_xi_solo_cells_dims (g_rbp_api.p_rbp_results_xi_solo_cells_dims)
#define rbp_results_xi_solo_dims (g_rbp_api.p_rbp_results_xi_solo_dims)
#define rbp_results_yhat_cells_dims (g_rbp_api.p_rbp_results_yhat_cells_dims)
#define rbp_results_ysolo_cells_dims (g_rbp_api.p_rbp_results_ysolo_cells_dims)
#define rbp_results_ysolo_distribution_dims (g_rbp_api.p_rbp_results_ysolo_distribution_dims)
#define rbp_set_percentile_value_algorithm (g_rbp_api.p_rbp_set_percentile_value_algorithm)
#define rbp_set_percentile_value_algorithm_str (g_rbp_api.p_rbp_set_percentile_value_algorithm_str)
#define rbp_similarity (g_rbp_api.p_rbp_similarity)
#endif

#ifdef __cplusplus
}
#endif

#endif
